# site settings
title: Yubin Kim
subtitle: 
email: ybkim95@media.mit.edu
description: I am currently a visiting student at Personal Robots Group at MIT Media Lab. My research interests lie in the area of personalized human-robot interaction for elders and children, multi-person dialogue system and reinforcement learning. I love to solve practical problems that happens in our daily lives and develop robots for that purposes.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ybkim95.github.io/ # the base hostname & protocol for your site
author: Yubin Kim
street_address: 143 Albany St
city: Cambridge
state: MA
zip_code: 02139
country: USA
phone: (617) 251-1764

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ybkim95
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram: 
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
